<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\CodeSwitchX.Ingest\CodeSwitchX.Ingest.csproj" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
