// <auto-generated />
using System;
using CodeSwitchX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeSwitchX.Data.Migrations
{
    [DbContext(typeof(CodeSwitchXDbContext))]
    partial class CodeSwitchXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CodeSwitchX.Core.Persistence.PricingRule", b =>
                {
                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("CacheReadPerM")
                        .HasColumnType("REAL");

                    b.Property<double>("CacheWritePerM")
                        .HasColumnType("REAL");

                    b.Property<long>("ContextWindow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<double>("InputPerM")
                        .HasColumnType("REAL");

                    b.Property<double>("OutputPerM")
                        .HasColumnType("REAL");

                    b.HasKey("Model");

                    b.ToTable("PricingRules");
                });

            modelBuilder.Entity("CodeSwitchX.Core.Persistence.SessionEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("SessionId", "At");

                    b.ToTable("SessionEvents");
                });

            modelBuilder.Entity("CodeSwitchX.Core.Persistence.SessionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClaudePid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContextCacheRead")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContextCacheWrite")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContextInput")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContextOutput")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cwd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Inferred")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastEventAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastNotification")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastToolName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("StateSince")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TitleLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranscriptPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastEventAt");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CodeSwitchX.Core.Persistence.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("CodeSwitchX.Core.Persistence.TranscriptCursor", b =>
                {
                    b.Property<string>("Path")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteOffset")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastWriteUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Path");

                    b.ToTable("TranscriptCursors");
                });

            modelBuilder.Entity("CodeSwitchX.Core.Persistence.UsageBucket", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("MinuteUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheRead")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheWrite")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Input")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Output")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "Model", "MinuteUtc");

                    b.HasIndex("MinuteUtc");

                    b.ToTable("UsageBuckets");
                });

            modelBuilder.Entity("CodeSwitchX.Core.Workspaces.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("CodeSwitchX.Core.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VsCodeProfile")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceFile")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RootPath")
                        .IsUnique();

                    b.HasIndex("TrackId");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("CodeSwitchX.Core.Workspaces.Worktree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Worktrees");
                });

            modelBuilder.Entity("CodeSwitchX.Core.Workspaces.Workspace", b =>
                {
                    b.HasOne("CodeSwitchX.Core.Workspaces.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeSwitchX.Core.Workspaces.Worktree", b =>
                {
                    b.HasOne("CodeSwitchX.Core.Workspaces.Workspace", null)
                        .WithMany("Worktrees")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeSwitchX.Core.Workspaces.Workspace", b =>
                {
                    b.Navigation("Worktrees");
                });
#pragma warning restore 612, 618
        }
    }
}
