<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\CodeSwitchX.Core\CodeSwitchX.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CodeSwitchX.Conductor.Tests" />
  </ItemGroup>
</Project>
